apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ${{values.app_name}}
  description: Service ${{values.app_name}}

  annotations:
    github.com/project-slug: jk7testorg/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: jk7test/${{values.app_name | trim}}/main
    argocd/app-name: ${{ values.app_name | lower }}-${{ values.app_env }}
    backstage.io/kubernetes-id: ${{values.app_name}}
    sonarqube.org/project-key: ${{ values.app_name | lower }}
    prometheus.io/rule: "kube_pod_container_resource_requests{pod=~'${{ values.app_name | lower }}.*'}|resource,kube_pod_container_status_running{pod=~'${{ values.app_name | lower }}.*'}|container"
    #prometheus.io/alert: "KubePodCrashLooping,KubeDeploymentReplicasMismatch,KubePodNotReady,KubeContainerWaiting,KubeContainerOOMKilled,KubeDeploymentRolloutStuck" #,KubeJobFailed"
    prometheus.io/alert: "all"
    prometheus.io/labels: "namespace=${{ values.app_env | lower }}"

spec:
  type: service
  owner: development
  lifecycle: experimental

# apiVersion: backstage.io/v1alpha1
# kind: Component

# metadata:
#   name: ${{values.app_name}}
#   description: Service ${{values.app_name}}

#   annotations:
#     github.com/project-slug: BackstageSSPPoC/${{values.app_name}}
#     backstage.io/techdocs-ref: dir:.
#     jenkins.io/job-full-name: Backstage_SSP_PoC/${{values.app_name | trim}}/main
#     argocd/app-name: ${{ values.app_name | lower }}
#     backstage.io/kubernetes-id: ${{values.app_name}}
#     sonarqube.org/project-key: ${{ values.app_name | lower }}

# spec:
#   type: service
#   owner: development
#   lifecycle: experimental
