pipeline {
    agent any
    
    environment {
        APP_NAME = "${{values.app_name}}".toLowerCase().trim()
        DOCKER_IMAGE = "jaykumark7/${APP_NAME}"
        DOCKER_TAG = "1.0.${BUILD_NUMBER}"
        IMAGE_TAG = "${DOCKER_IMAGE}:${DOCKER_TAG}"
        GITOPS_REPO = "https://github.com/jk7testorg/k8s-manifest.git"
        APP_PORTS = "${{values.app_port}}"
        DEPLOY_ENV = "${{values.app_env}}"       
        DEPLOY_NAMESPACE = "${{values.app_env}}"
    }
    
    stages {
    
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
    
        stage('Decide Pipeline Flow') {
            steps {
                script {
    
                    echo "Branch: ${env.BRANCH_NAME}"
                    echo "GIT_BRANCH: ${env.GIT_BRANCH}"
    
                    // ✅ MAIN → CI + CD
                    if (env.BRANCH_NAME == "main" || env.BRANCH_NAME.endsWith("/main") || env.GIT_BRANCH?.endsWith("main")) {
                        echo "Main branch detected → CI + CD"
                        env.RUN_MODE = "cd"
                    } 
                    // ✅ ANY OTHER BRANCH → CI ONLY
                    else {
                        echo "Non-main branch → CI only"
                        env.RUN_MODE = "ci"
                    }
                }
            }
        }
    
// ================= CI STAGES =================
    
        stage('Install Dependencies') {
            steps {
                script {
                    if (fileExists('package.json')) {
                        sh 'npm install'
                    } else {
                        echo "No package.json found"
                    }
                }
            }
        }
    
        stage('Run Tests') {
            steps {
                script {
                    if (fileExists('package.json')) {
                        sh 'npm test || true'
                    } else {
                        echo "Skipping tests"
                    }
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                    npx sonar-scanner \
                      -Dsonar.projectKey=${APP_NAME} \
                      -Dsonar.sources=.
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    
// ================= CD STAGES =================

        stage('Build Docker Image') { 
                when { 
                    expression { env.RUN_MODE == "cd" } 
                } 
                steps { 
                    sh 'docker build -t ${IMAGE_TAG} .' 
                } 
        }
    
        stage('Login to Docker Hub') {
            when {
                expression { env.RUN_MODE == "cd" }
            }
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'jk7-dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }
    
        stage('Push Docker Image') {
            when {
                expression { env.RUN_MODE == "cd" }
            }
            steps {
                sh 'docker push ${IMAGE_TAG}'
            }
        }
    
        stage('Update GitOps Repo') {
            when {
                expression { env.RUN_MODE == "cd" }
            }
            steps {
                withCredentials([string(credentialsId: 'jk7-github-token', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    rm -rf k8s-manifest
    
                    git clone --depth 1 https://${GITHUB_TOKEN}@github.com/jk7testorg/k8s-manifest.git
                    cd k8s-manifest
    
                    # Environment specific folder
                    mkdir -p apps/${APP_NAME}/${DEPLOY_ENV}
                    # application.yaml argocd folder me
                    mkdir -p argocd/
                    cp ../manifest-templates/application.yaml argocd/${APP_NAME}-${DEPLOY_ENV}.yaml || true
                    
                    # deployment/service/ingress apps folder me
                    mkdir -p apps/${APP_NAME}/${DEPLOY_ENV}
                    cp ../manifest-templates/deployment.yaml apps/${APP_NAME}/${DEPLOY_ENV}/ || true
                    cp ../manifest-templates/service.yaml apps/${APP_NAME}/${DEPLOY_ENV}/ || true
                    cp ../manifest-templates/ingress.yaml apps/${APP_NAME}/${DEPLOY_ENV}/ || true

                    # Replace all placeholders
                    sed -i "s|\\${APP_NAME}|${APP_NAME}|g" apps/${APP_NAME}/${DEPLOY_ENV}/*.yaml || true
                    sed -i "s|\\${DOCKER_IMAGE}|${IMAGE_TAG}|g" apps/${APP_NAME}/${DEPLOY_ENV}/*.yaml || true
                    sed -i "s|\\${APP_PORT}|${APP_PORTS}|g" apps/${APP_NAME}/${DEPLOY_ENV}/*.yaml || true
                    sed -i "s|\\${NAMESPACE}|${DEPLOY_NAMESPACE}|g" apps/${APP_NAME}/${DEPLOY_ENV}/*.yaml || true
                    sed -i "s|\\${APP_NAME}|${APP_NAME}|g" argocd/${APP_NAME}-${DEPLOY_ENV}.yaml || true
                    sed -i "s|\\${NAMESPACE}|${DEPLOY_NAMESPACE}|g" argocd/${APP_NAME}-${DEPLOY_ENV}.yaml || true

                    git config user.email "jenkins@local"
                    git config user.name "jenkins"
                    git add .
                    git commit -m "[${DEPLOY_ENV}] Deploy ${APP_NAME} build ${BUILD_NUMBER}" || echo "No changes"
                    git push origin main
                    '''
                }
            }
        }
    }
    
    post {
        always {
            sh "docker logout || true"
            sh "docker image prune -f || true"
        }
    }
}
